name: master_detail_flow
description: A package designed to help you easily create sleek, responsive master-detail flows.
version: 3.0.0
repository: https://github.com/2-5-perceivers/flutter-master-detail-flow
funding:
  - https://github.com/sponsors/rares45
  - https://buymeacoffee.com/raresvanca
topics:
  - responsive
  - material
  - navigation
  - layout
screenshots:
  - description: Switching between detail pages
    path: images/demo.gif

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  animations: ^2.0.7
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
