name: master_detail_flow
description: A package that provides a simple master-detail-flow with material 3
version: 3.0.0
repository: https://github.com/2-5-perceivers/flutter-master-detail-flow

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  animations: ^2.0.7
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
